# This file stores configurations for your Shopify app.

scopes = "write_products, write_themes, write_delivery_customizations, write_checkouts, read_checkouts, write_pixels, read_customer_events, read_customer_merge, write_customer_merge, read_customers, write_customers"
